### ISSUE TITLE
Older version in PYPI

### ISSUE THREAD

**Issue by shinderohitt** [rsgalloway/instapaper#2]
Hey @rsgalloway,

This is unrelated to the project work present here, but, the latest version available for instapaper in PYPI is `0.2`, which looks older.

It would be great if you publish `0.3` on PYPI -- assuming there have been fixes/improvements since `0.2`.

**Comment by rsgalloway** [comment]
Hi Rohitt, Ah, sorry, simple oversight. I will publish 0.3. Yes, there have been several updates since 0.2.

**Comment by rsgalloway** [comment]
https://pypi.python.org/pypi?:action=display&name=instapaper&version=0.3
