### ISSUE TITLE
Please release a new version on PyPI

### ISSUE THREAD

**Issue by alexwlchan** [rsgalloway/instapaper#5]
If I try to install this library from PyPI, there are two annoying problems that are fixed on master:

* No Python 3 support
* The `oauth2` dependency isn’t installed by default

I can `pip install` from the Git repo, but it would be nicer if I could install from a (fixed, stable) version on PyPI instead. Please could you cut a new release?

**Comment by rsgalloway** [comment]
Will do once Issue #6 is resolved!

**Comment by qiuwch** [comment]
Hi, @rsgalloway 

Since #6 is fixed. Can you release a new version to pypi? The existing version can not support python 3. Thanks.

**Comment by rsgalloway** [comment]
done! sorry for the delay.
