### ISSUE TITLE
dehtml() function prints an AttributeError in Python 3

### ISSUE THREAD

**Issue by alexwlchan** [rsgalloway/instapaper#6]
Consider the following example program:

```python
import instapaper

api = instapaper.Instapaper(oauthkey=OAUTHKEY, oauthsec=OAUTHSEC)
api.login(username=USERNAME, password=PASSWORD)

bookmarks = api.bookmarks(folder='unread')
b = bookmarks[0]
b.text
```

When run, this prints an `AttributeError` to the console:

```console
$ python3 demo.py
Traceback (most recent call last):
  File "/private/tmp/ip/lib/python3.5/site-packages/instapaper.py", line 114, in dehtml
    text = text.decode('UTF-8')
AttributeError: 'str' object has no attribute 'decode'
```

It would be better if the module coped with this case more gracefully – I think it would be enough to replace `text = text.decode('UTF-8')` with

```python
try:
    text = text.decode('UTF-8')
except AttributeError:
    pass
```

but I haven’t tried it properly.

(Also, printing a traceback rather than throwing the exception made this more frustrating to debug.)

**Comment by rsgalloway** [comment]
I think it only prints the exception instead of raising it because it still returns the original text. Of course that could be changed if that's bad behavior. 

I've pushed a potential fix for this to the "issue-6" branch, try it out let me know.

**Comment by alexwlchan** [comment]
Hmm. If I run my example program on Python 3, I get a different error now:

```console
$ python demo.py
Traceback (most recent call last):
  File "/Users/alexwlchan/repos/instapaper/instapaper.py", line 113, in dehtml
    text = str(text, 'UTF-8')
TypeError: decoding str is not supported
```

I think the correct behaviour here is to pass through `text` unmodified – i.e., the patch should be

```python
if sys.version_info < (3, 0):
    text = text.decode('utf-8')
```

In Python 2, `text` is a bytestring, so we need to decode it to Unicode before passing it up the stack. But Python 3 is dealing with Unicode strings natively, so it’s already been decoded for us.

**Comment by Barabazs** [comment]
I confirm that the fix from @alexwlchan works as expected. Please see PR #8 for an updated version.
